global:
  scrape_interval: 5s

scrape_configs:
  - job_name: gate
    static_configs:
      - targets: ["gate:8000"]
  - job_name: training
    static_configs:
      - targets: ["training:8000"]
  - job_name: serving
    static_configs:
      - targets: ["serving:8000"]
